### PR TITLE
changes made to tables to support oauth and new seeds to match tables

### PR DESCRIPTION
**Pull request by vpagano10**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by MsMaddyMac** [comment]
Update .insert and .update methods in models to have "id" passed as a second parameter to avoid 500 error when hitting the deployed endpoints.

**Comment by josharmantrout91** [comment]
[Admin: can delete existing user](https://trello.com/c/hp5TFdBK/93-admin-can-delete-existing-user)

**Comment by josharmantrout91** [comment]
[Admin: can search users by id](https://trello.com/c/e3PvxiUy/94-admin-can-search-users-by-id)

**Comment by josharmantrout91** [comment]
[Admin: can edit existing user info](https://trello.com/c/Ry02vVIE/92-admin-can-edit-existing-user-info)

**Pull request merged**
